version: '3'
services:
  rust:
    build: rust_project
    container_name: 'rust'
    tty: true
    volumes:
      - "./rust_project:/rust_project"
  npm:
    build: npm_project
    container_name: 'npm'
    tty: true
    volumes:
      - "./npm_project:/npm_project"